# Page settings
baseURL = "https://www.focalboard.com/"
canonifyURLs = true
#relativeURLs = true

title = "Focalboard: Open source alternative to Trello, Asana, and Notion"
languageCode = "en-us"
publishDir = "../docs"
pygmentsCodeFences = true
pygmentsStyle = "manni"

[taxonomies]
  category = "categories"

[params]
  # Meta
  author = ""
  description = ""
  email = ""
  ghrepo = "https://github.com/mattermost/focalboard/"

  [params.mailinglist]
    enable = false

  [params.notification]
    enable = false
    url = "https://mattermost.com/careers"
    text = "We're hiring!"

  [params.search]
    enable = false

  [[params.sidebar.item]]
    name = "download"
    displayName = "Download"
    draft = false

  [[params.sidebar.item]]
    name = "guide"
    displayName = "User's Guide"
    draft = false

  [params.sidebar]
  [[params.sidebar.item]]
    name = "contribute"
    displayName = "Contribute"
    draft = false

  # Navigation
  [params.navigation]
    brand = "Focalboard"
    home = "Home"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/download/personal-edition"
      name = "Download"
      weight = 1

    [[menu.postpend]]
      url = "/guide/user"
      name = "User's Guide"
      weight = 2

    [[menu.postpend]]
      url = "/contribute/getting-started"
      name = "Contribute"
      weight = 3

    [[menu.postpend]]
      url = "/blog"
      name = "Blog"
      weight = 4

    [[menu.postpend]]
      url = "/feedback"
      name = "Feedback"
      weight = 5

    # Workaround to add draft status to menu items
    [[params.navigation.drafts]]
      Download = false
      "User's Guide" = false
      Contribute = false
      Integrate = false
      Extend = false
      Blog = false
      Feedback = false
      Internal = false
      'Admin Docs' = false

  # Hero section
  [params.hero]
    title = "Get Focalboard"
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  [[params.intro.item]]
    title = "Download"
    description = "Download Focalboard here."
    url = "download/personal-edition"
    button = "Download Now"
    icon = "/img/download-icon.svg"
    draft = false

  [[params.intro.item]]
    title = "Read Guide"
    description = "Read the User's Guide to ge the most out of Focalboard."
    url = "guide/user"
    button = "User's Guide"
    icon = "/img/use-icon.svg"
    draft = false

  [[params.intro.item]]
    title = "Contribute"
    description = "Help build the future of productivity and submit code directly to the Focalboard open-source project."
    url = "contribute/getting-started"
    button = "Start Contributing"
    icon = "/img/contribute-icon.svg"
    draft = false

  # Footer section
  [params.footer]
    enable = true
  	twitter = 'https://twitter.com/Focalboard'
  	facebook = 'https://www.facebook.com/Mattermost-2300985916642531/'
  	youtube = 'https://www.youtube.com/channel/UCNR05H72hi692y01bWaFXNA'
    copyright = '&copy; Mattermost, Inc. All Rights Reserved.'

# Allows html in Hugo >= v0.60.0.  See Github issue #506.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
