---

title: "Mattermost Focalboard"
copyright: "Â©2015-present Mattermost,Inc. All Rights Reserved. See LICENSE for license information."
description: "This document includes a list of open source components used in Mattermost Focalboard, including those that have been modified."
search:
  - "server/go.mod"
  - "linux/go.mod"
dependencies: []
devDependencies: []

...
