name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

jobs:

  ci-ubuntu-server:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        db:
          - sqlite
          - mysql
          - postgres

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm ci
      run: cd webapp; npm ci

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Linux server
      run: make server-linux-package

    - name: Copy server binary for Cypress
      run: cp bin/linux/focalboard-server bin/

    - name: "Test server: ${{matrix['db']}}"
      run: make server-test-${{matrix['db']}}

  ci-ubuntu-webapp:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: npm ci
      run: cd webapp; npm ci

    - name: ESLint
      run: cd webapp; npm run check

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.1.0

    - name: Build Linux server
      run: make server-linux-package

    - name: Copy server binary for Cypress
      run: cp bin/linux/focalboard-server bin/

    - name: Upload server package
      uses: actions/upload-artifact@v1
      with:
        name: focalboard-server-linux-amd64.tar.gz
        path: ${{ github.workspace }}/dist/focalboard-server-linux-amd64.tar.gz

    - name: "Test webapp: Jest"
      run: cd webapp; npm run test

    - name: "Test webapp: Cypress"
      run: "cd webapp; npm run cypress:ci"
