name: golangci-lint

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]

jobs:
  golangci:
    name: plugin
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - uses: actions/checkout@v3
      - name: plugin-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          working-directory: mattermost-plugin
          skip-go-installation: true
