name: golangci-lint

on:
  push:
    branches: [ main, release-** ]
  pull_request:
    branches: [ main, release-** ]
  workflow_dispatch:

jobs:
  golangci:
    name: plugin
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - uses: actions/checkout@v3
      - name: set up golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
      - name: lint
        run: make server-lint
